In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
companies= pd.read_csv("./data/01_raw/companies.csv")

In [6]:
df

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100%,Isle of Man,1.0,f
1,46728,100%,NaN,1.0,f
2,34618,38%,Isle of Man,1.0,f
3,28619,100%,Bosnia and Herzegovina,1.0,f
4,8240,NaN,Chile,1.0,t
...,...,...,...,...,...
10014,20213,NaN,Russian Federation,1.0,f
10015,2235,100%,Guinea,1.0,f
10016,2353,100%,Senegal,2.0,t
10017,49772,100%,Jersey,1.0,f
10018,16548,90%,NaN,2.0,f

In [7]:
df.describe()

                 id  total_fleet_count
count  10019.000000       10017.000000
mean   25038.690788           1.844464
std    14445.346466          12.446153
min        1.000000           1.000000
25%    12610.000000           1.000000
50%    24858.000000           1.000000
75%    37547.000000           1.000000
max    50098.000000        1105.000000

In [10]:
def parse_percentage(x: pd.Series) -> pd.Series:
    x = x.str.replace("%","")
    x = x.astype(float) / 100
    return x

In [14]:
parse_percentage(companies["company_rating"])

0        1.00
1        1.00
2        0.38
3        1.00
4         NaN
         ...
10014     NaN
10015    1.00
10016    1.00
10017    1.00
10018    0.90
Name: company_rating, Length: 10019, dtype: float64